## Numpy

8 bits = 1 Byte
2^n ile hsaplanır ve python 2^64 bits hesaplar.
numpy int8 yani 2^8 bits hesaplamalarını yapar. (0-255 byte)

In [2]:
# pip install numpy

In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
array_a = np.array([1,2,3,4,5])

In [6]:
array_b = np.array([0, .5, 1, 1.5, 2. ])

In [7]:
array_a[0]

1

In [8]:
array_b[-1]

2.0

In [9]:
array_a[:2]

array([1, 2])

In [10]:
array_a.dtype

dtype('int32')

In [11]:
array_b.dtype

dtype('float64')

In [12]:
empty_array = np.array([])

In [13]:
empty_array.dtype

dtype('float64')

In [14]:
np.array([1, 2, 3, 4 ], dtype=np.float_) # int listeyi -> float a dönüştürür

array([1., 2., 3., 4.])

In [15]:
np.array([1, 2, 3, 4 ], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [16]:
array_c = np.array(["ada", "lovelace"])

In [17]:
array_c.dtype

dtype('<U8')

### Dimension and shapes

In [18]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
array_a.shape

(5,)

In [20]:
my_array.shape # 2 satır, 3 sütun

(2, 3)

In [21]:
array_a.ndim # boyut

1

In [22]:
my_array.ndim

2

In [23]:
my_array.size # her bir değerin kaç tane olduğu sayısını verir

6

In [31]:
your_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
    
])

In [32]:
your_array.ndim

3

In [33]:
your_array.shape # matrix boyutlarının tutarlı olması gerekiyor

(2, 2, 3)

In [34]:
your_array.size

12

indexing and slicing

In [35]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [36]:
my_array[1]

array([4, 5, 6])

In [37]:
my_array[1][0]

4

In [39]:
my_array[1, 0] #1.index in sıfırıncısıı

4

In [40]:
my_array[0:2] # yukarıdan aşağıya

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
my_array[:2, :2] # yukarıdan aşağıya ve soldan sağa ilk 2 elamnı yazdırır

array([[1, 2],
       [4, 5]])

In [43]:
my_array[1] = np.array([10, 10, 10])

In [44]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [45]:
my_array[2] = 99

In [46]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [49]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
my_array = np.arange(0,10) # 1,10 da çalışmaz
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [59]:
np.zeros(5) # içine tuple vermemiz gerekiyor

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [63]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.eye(5,5) # 1 ler diagonal yerleşir

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
my_array = np.random.random((5,2)) # random float değerler
print(my_array)

[[0.27156994 0.66925639]
 [0.19609818 0.03014151]
 [0.38413298 0.403368  ]
 [0.08669626 0.99892262]
 [0.25565266 0.77527945]]


In [71]:
np.random.randint(100, size=(5,5)) # random integer değerler

array([[ 7, 44, 80, 18, 41],
       [12,  6, 68, 18, 27],
       [32, 90, 55, 77, 92],
       [ 9, 96, 36, 90, 82],
       [ 3, 58, 92, 18, 44]])

In [74]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [75]:
# any(), all(), full(), concatenate() iki listeyi(python nesenesi ve liste de olabilir) birbirine eklyerek birleştirir, 

In [79]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
np.any(array1)

True

In [84]:
np.all(array1)

False

In [85]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
np.concatenate([array1, array1], axis=1) # ön tanımlı axis 0 dır

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### statistics

In [100]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
array1.sum()

45

In [102]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
array1.sum()

45

In [104]:
array1.mean()

4.5

In [105]:
array1.std()

2.8722813232690143

In [106]:
array1.var()

8.25

In [107]:
array1.sum(axis=1) # satırları toplar

array([10, 35])

In [108]:
array1.sum(axis=0) # sütunları toplar

array([ 5,  7,  9, 11, 13])

In [109]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
# orjinal değeri etkilemesi için atama yapılmalı
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
array2 = np.arange(0, 10)
array2 = array2.reshape(5, 2)
array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

boolean arrays

In [114]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [115]:
a[0], a[-1] # tek boyutlularda doğrudan elemanı verir

(0, 3)

In [116]:
a[[0, -1]] # yeni bir array olarak ekler

array([0, 3])

In [117]:
a[[True, False, False, True]] # boolean olarak elemanları alalım

array([0, 3])

Comparison Operators

In [119]:
a

array([0, 1, 2, 3])

In [120]:
a >= 2

array([False, False,  True,  True])

In [122]:
a[a >=2 ]

array([2, 3])

In [123]:
a.mean()

1.5

In [124]:
a[~(a > a.mean())]

array([0, 1])

In [125]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [126]:
a[(a == 0) & (a == 1)] # hem 0 hem 1 e eşit değer olamaz

array([], dtype=int32)

In [128]:
a[(a <= 2) & (a % 2 == 0)] # 2 den küçük ve 2 ye tam bölünebilen sayılar

array([0, 2])

In [130]:
# 100 e kadar rastgele tam sayılardan oluşan 3,3 bir matris oluşturalım
# 30'dan büyük olanları boolean yöntemi ile filtreleyin
our_array = np.random.randint(100, size=(3,3))
# our_array[our_array > 30]

array([36, 76, 42, 33])

In [133]:
np.random.randint(0, 100, size = 9, dtype= int).reshape(3,3)

array([[28, 13, 62],
       [ 4, 49, 22],
       [41, 60,  2]])

In [131]:
boolean_array = our_array > 30
boolean_array

array([[False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [132]:
our_array[boolean_array]

array([36, 76, 42, 33])

In [134]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [135]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [136]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [137]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [138]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [139]:
import sys

In [140]:
sys.getsizeof(10)

28

In [141]:
sys.getsizeof(1000**100)

160

In [142]:
np.dtype(int).itemsize

4

In [143]:
np.dtype(np.int8).itemsize

1

In [144]:
np.dtype(float).itemsize

8

In [146]:
sys.getsizeof([])

56

In [145]:
sys.getsizeof([1, 2, 3])

88

In [147]:
np.array([1, 2, 3]).nbytes

12

In [148]:
my_list = list(range(100000))

In [149]:
my_array = np.arange(100000)

In [152]:
%time np.sum(my_array ** 2) # micro sn

CPU times: total: 0 ns
Wall time: 1.03 ms


216474736

In [153]:
%time sum([number ** 2 for number in my_list]) # mili sn yani daha uzun sürdü

CPU times: total: 62.5 ms
Wall time: 168 ms


333328333350000