In [1]:
number = 15

In [2]:
type(number)

int

In [3]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [4]:
my_list = [1, 2, 3]
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Numpy

8 bits = 1 Byte
2^n ile hsaplanır ve python 2^64 bits hesaplar.
numpy int8 yani 2^8 bits hesaplamalarını yapar. (0-255 byte)

In [5]:
# pip install numpy
# pip3 install numpy

In [6]:
import numpy as np

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
array_a = np.array([1,2,3,4,5])

In [9]:
array_b = np.array([0, .5, 1, 1.5, 2. ])

In [10]:
array_a[0]

1

In [11]:
array_b[-1]

2.0

In [12]:
array_a[:2]

array([1, 2])

In [13]:
array_a.dtype

dtype('int32')

In [17]:
arrar_a = np.array([1, 2, 3, 4], dtype=np.int64)
print(arrar_a.dtype)

int64


In [14]:
array_b.dtype

dtype('float64')

In [15]:
empty_array = np.array([])

In [16]:
empty_array.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4 ], dtype=np.float_) # int listeyi -> float a dönüştürür

array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4 ], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
array_c = np.array(["ada", "lovelace"])

In [21]:
array_c.dtype

dtype('<U8')

### Dimension and shapes

In [22]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [23]:
array_a.shape

(5,)

In [24]:
my_array.shape # 2 satır, 3 sütun

(2, 3)

In [25]:
array_a.ndim # boyut

1

In [26]:
my_array.ndim

2

In [27]:
my_array.size # her bir değerin kaç tane olduğu sayısını verir

6

In [28]:
your_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
    
])

In [29]:
your_array.ndim

3

In [30]:
your_array.shape # matrix boyutlarının tutarlı olması gerekiyor

(2, 2, 3)

In [31]:
your_array.size

12

indexing and slicing

In [32]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [33]:
my_array[1]

array([4, 5, 6])

In [34]:
my_array[1][0]

4

In [35]:
my_array[1, 0] #1.index in sıfırıncısıı

4

In [36]:
my_array[0:2] # yukarıdan aşağıya

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
my_array[:2, :2] # yukarıdan aşağıya ve soldan sağa ilk 2 elamnı yazdırır

array([[1, 2],
       [4, 5]])

In [38]:
my_array[1] = np.array([10, 10, 10])

In [39]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [40]:
my_array[2] = 99

In [41]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [43]:
my_array = np.arange(0,10) # 1,10 da çalışmaz
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [46]:
np.zeros(5) # içine tuple vermemiz gerekiyor

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.eye(5,5) # 1 ler diagonal yerleşir

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
my_array = np.random.random((5,2)) # random float değerler
print(my_array)

[[0.5951633  0.2880548 ]
 [0.88144352 0.07011243]
 [0.58884405 0.27958976]
 [0.70113106 0.01717574]
 [0.46019461 0.0747002 ]]


In [54]:
np.random.randint(100, size=(5,5)) # random integer değerler

array([[74, 82,  2, 22,  9],
       [87, 47, 92, 61, 55],
       [ 0, 17,  8, 49, 69],
       [47, 60, 51, 20, 25],
       [45, 45, 49, 79,  4]])

In [55]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [56]:
# any(), all(), full(), concatenate() iki listeyi(python nesenesi ve liste de olabilir) birbirine eklyerek birleştirir, 

In [57]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
np.any(array1)

True

In [60]:
np.all(array1)

False

In [61]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
np.concatenate([array1, array1], axis=1) # ön tanımlı axis 0 dır

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### statistics

In [63]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array1.sum()

45

In [65]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
array1.sum()

45

In [67]:
array1.mean()

4.5

In [68]:
array1.std()

2.8722813232690143

In [69]:
array1.var()

8.25

In [70]:
array1.sum(axis=1) # satırları toplar

array([10, 35])

In [71]:
array1.sum(axis=0) # sütunları toplar

array([ 5,  7,  9, 11, 13])

In [72]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
# orjinal değeri etkilemesi için atama yapılmalı
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
array2 = np.arange(0, 10)
array2 = array2.reshape(5, 2)
array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

boolean arrays

In [76]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [77]:
a[0], a[-1] # tek boyutlularda doğrudan elemanı verir

(0, 3)

In [78]:
a[[0, -1]] # yeni bir array olarak ekler

array([0, 3])

In [79]:
a[[True, False, False, True]] # boolean olarak elemanları alalım

array([0, 3])

Comparison Operators

In [80]:
a

array([0, 1, 2, 3])

In [81]:
a >= 2

array([False, False,  True,  True])

In [82]:
a[a >=2 ]

array([2, 3])

In [83]:
a.mean()

1.5

In [84]:
a[~(a > a.mean())]

array([0, 1])

In [85]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [86]:
a[(a == 0) & (a == 1)] # hem 0 hem 1 e eşit değer olamaz

array([], dtype=int32)

In [87]:
a[(a <= 2) & (a % 2 == 0)] # 2 den küçük ve 2 ye tam bölünebilen sayılar

array([0, 2])

* 100 e kadar rastgele tam sayılardan oluşan 3,3 bir matris oluşturalım
* 30'dan büyük olanları boolean yöntemi ile filtreleyin

In [88]:
# 100 e kadar rastgele tam sayılardan oluşan 3,3 bir matris oluşturalım
# 30'dan büyük olanları boolean yöntemi ile filtreleyin
our_array = np.random.randint(100, size=(3,3))
# our_array[our_array > 30]

In [89]:
np.random.randint(0, 100, size = 9, dtype= int).reshape(3,3)

array([[88, 94,  6],
       [39, 47, 80],
       [31, 44, 41]])

In [90]:
boolean_array = our_array > 30
boolean_array

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [91]:
our_array[boolean_array]

array([40, 60, 81, 64, 54, 63])

In [92]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [93]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [96]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [97]:
import sys

In [98]:
sys.getsizeof(10)

28

In [99]:
sys.getsizeof(1000**100)

160

In [100]:
np.dtype(int).itemsize

4

In [101]:
np.dtype(np.int8).itemsize

1

In [102]:
np.dtype(float).itemsize

8

In [103]:
sys.getsizeof([])

56

In [104]:
sys.getsizeof([1, 2, 3])

88

In [105]:
np.array([1, 2, 3]).nbytes

12

In [106]:
my_list = list(range(100000))

In [107]:
my_array = np.arange(100000)

In [108]:
%time np.sum(my_array ** 2) # micro sn

CPU times: total: 0 ns
Wall time: 162 ms


216474736

In [109]:
%time sum([number ** 2 for number in my_list]) # mili sn yani daha uzun sürdü

CPU times: total: 15.6 ms
Wall time: 52.1 ms


333328333350000